### ISSUE TITLE
docs: 📝 first iteration of requirements

### ISSUE THREAD

**Issue by iKinoo** [ChusoAndKino-Limited/POO-2023-LIS#22]
[Whiteboard](https://alumnosuady-my.sharepoint.com/:wb:/g/personal/a19203594_alumnos_uady_mx/EZcsIskiHN9DkN_dlX-9oQwB6TNOO0s-lUyBX6t4QbcW-w?e=9I8fne)

**Comment by iKinoo** [comment]
(In Spanish)
<details>
<summary>Requirements</summary>

- Como usuario quiero elegir una patrón de diseño de una lista para ver su definición

- Como usuario quiero ver un ejemplo real del patrón de diseño para saber donde se utiliza realmente.

- administrador quiero publicar nuevos ejemplos de de un patron de diseño.

- como administrador quiero editar un ejemplo de la lista de ejemplos de un patron de diseño.

- como administrador quiero elminar un ejemplo de la lista de ejemplos para podergith
</details>

**Comment by MarcoSIIIU** [comment]
New requirements
[Requirements.md](https://github.com/ChusoAndKino-Limited/POO-2023-LIS/files/12745365/Requirements.md)

**Comment by iKinoo** [comment]
Looks good, still left some artifacts but we will follow up on this

**Comment by MarcoSIIIU** [comment]
Functional and non-functional requirements are added
[Requirements.md](https://github.com/ChusoAndKino-Limited/POO-2023-LIS/files/12773857/Requirements.md)
